development:
		host: mysql.lookingforpullrequests.com
		name: lfpr_dev
		user: lfpr_user
		pwd: infotecdoglio23

production:
		host: localhost
		name: lfpr_prod
		user: lfpr
		pwd: l00k1ng4p00lr3qu3s7

